### PR TITLE
Rudimentary Macroparadise plugin

### PR DESCRIPTION
**Pull request by megri**

### CODE REVIEW

**Comment by cvogt** [comment]
love it. Ideal would be a follow up commit or PR, that adds your experiment to the `examples/` folder

**Comment by megri** [comment]
Is it ok in its raw adulterated form as shown on megri/cbt-test?

**Comment by cvogt** [comment]
yes. ideally add a line here to check it produces the right output: https://github.com/cvogt/cbt/blob/master/test/test.scala#L424

and if you want to turn it into a single build file multi-project build, that might be nice :)

**Comment by cvogt** [comment]
Gave it another look. How is this different from the existing Scala paradise plugin?

**Comment by cvogt** [comment]
Except for better implementation and version number?

**Comment by cvogt** [comment]
Should it maybe replace it?

**Comment by megri** [comment]
I believe Scalaparadise.scala enables scala.reflection-based (old-style) macros for Scala 2.10-projects and macro annotations for 2.11+.

Macroparadise.scala on the other hand enables scala.meta-style macros. I believe they are currently limited to macro annotations only.

**Comment by megri** [comment]
Updated the PR to use a single build.scala. Please review and comment on whether or not it looks sane :)

**Comment by megri** [comment]
Rebased PR on upstream

**Comment by megri** [comment]
Added the renaming as a separate commit. Can squash if desired

**Comment by cvogt** [comment]
Awesome. Merging

**Pull request merged**
