### PR TITLE
Added a cbt plugin for the kind-projector compiler plugin

### PR DESCRIPTION
**Pull request by etorreborre**
@cvogt is this all there is to do?

### CODE REVIEW

**Comment by cvogt** [comment]
@etorreborre yeah, happy to merge as is. even better would with with a small example project in /examples and triggering the example from the tests, similar to https://github.com/cvogt/cbt/pull/515

**Comment by cvogt** [comment]
fixed the compile error. I love how github now let's you push to branches of PRs opened against your repo

**Comment by etorreborre** [comment]
I tried to run the tests and I got:

```
~/projects/scala/cbt/test on kind-projector-plugin
± cbt run
Skipping slow tests
java.lang.Exception: Linting error in ./cbt bash launcher script:

	at cbt.test.Main$.cbtMain(test.scala:39)
	at cbt.test.Main.cbtMain(test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cbt.reflect.Module$$anonfun$typeStaticMethod$1.apply(reflect.scala:170)
	at cbt.reflect.StaticMethod.apply(StaticMethod.scala:4)
	at cbt_build.cbt.test.Build.run(build.scala:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by cvogt** [comment]
@etorreborre master is giving a better error message since yesterday or so. Basically you need to install `shellcheck` from brew or apt, etc

**Comment by etorreborre** [comment]
Ok, now I get
```scala
In /Users/etorreborre/projects/scala/cbt/cbt line 144:
JAVA_OPTS_CBT=($DEBUG -Xmx1536m -Xss10M -XX:MaxJavaStackTraceDepth=-1 -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xverify:none)
                                        ^-- SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
                                                                                             ^-- SC2191: The = here is literal. To assign by index, use ( [index]=value ) with no spaces. To keep as literal, quote it.
```

**Comment by cvogt** [comment]
@etorreborre that's fixed in master

**Comment by etorreborre** [comment]
I don't know what I'm doing wrong but I still get the same issue. Can you please try on your side on my PR?

**Comment by cvogt** [comment]
Ok, I just did. Seems like a new linting rule introduced by the latest shellcheck 0.4.6. Merging master into this PR fixed it.

**Comment by cvogt** [comment]
we should be good now :)

**Comment by etorreborre** [comment]
All green!

**Comment by cvogt** [comment]
@etorreborre nice, thx for the example :)!

**Comment by cvogt** [comment]
merged!

**Pull request merged**
