### PR TITLE
Change License to Apache 2.0

### PR DESCRIPTION
**Pull request by cvogt**
Following @fommil's advise I would like to change the license to Apache 2.0 

https://github.com/cvogt/cbt/issues/27

I'd like confirmation from all past (and very near future) contributors they are ok with this.

Confirmed: @tobias-johansson @farmdawgnation @hntd187 @paulp 
Pending confirmation: @tpolecat @chavxo @katrinsharp

Could you please confirm below?

Thx guys :)

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Good with me.

**Comment by hntd187** [comment]
I'm cool with this, I appreciate you asking too.

**Comment by paulp** [comment]
It would be a real thrill to stand in the way of a license change on the basis of the two or three characters I have contributed... but I won't.

**Comment by cvogt** [comment]
@paulp but you certainly don't fail to entertain ;). Thx

**Comment by fommil** [comment]
:stuck_out_tongue: btw, the licence used so far isn't even be able to stand in the way of **any** licence change. The joy of "permissive" licencing.

**Comment by paulp** [comment]
@fommil that's for the courts to decide!

**Comment by cvogt** [comment]
Sounds like this must have been useful to someone by the time anyone bothers suing. Sounds like mission accomplished.

**Comment by paulp** [comment]
"My software is so useful that someone bothered to sue me over it" is quite the pyrrhic victory but I applaud the positive attitude.

**Comment by fommil** [comment]
this is just the beginning, I have a PR in waiting to upgrade you to A++GPL

**Comment by cvogt** [comment]
is that the one where you have to share the source code of the brain of the developer if you make changes?

**Comment by fommil** [comment]
only the juicy bits. Obviously.

**Comment by tpolecat** [comment]
I have no opinion on (nor interest in) licensing questions, so this is fine with me.

**Comment by fommil** [comment]
btw, we use something like this for PRs in ensime-server. Easy to add your own https://cla-assistant.io/ensime/ensime-server?pullRequest=1349

**Comment by hntd187** [comment]
I am suing everyone on this project, please retain lawyers. :-o

**Comment by ChavXO** [comment]
Sounds fine.  :

**Comment by katrinsharp** [comment]
+1

**Comment by cvogt** [comment]
thx, guys

**Pull request merged**
