### PR TITLE
Support of relative symlinks to the cbt executable has been implemented.

### PR DESCRIPTION
**Pull request by buzden**
This is a fix for #583

### CODE REVIEW

**Comment by cvogt** [comment]
this broke OSX, pushing an adjustment

**Comment by buzden** [comment]
Okay. But I hope you understand that '-m' also makes everything work in case when there is a symlink to a symlink to the executable (and as many levels as you want). OSX workaround does not work with it. Are there any more kinds of canonicalization except '-m' which still work for OSX?

**Comment by cvogt** [comment]
I don't know. If there is a generally better solution I am all for it. For now I just made sure this doesn't break anything. You commit fixes linux, so now master is strictly better than it was before :). That's enough for me for now. As long as things improve, PRs don't need to deliver the perfect solution for what I am concerned.

**Comment by buzden** [comment]
> so now master is strictly better than it was before

Exactly so, no doubt! I'm so sorry not thinking about anyone except linuxers ;-)

I'm just saying that there probably will be a problem in the future and it will raise purely on OSX.

**Pull request merged**
