### PR TITLE
Rewrite Java 8 code in BootstrapScala.java in Java 7

### PR DESCRIPTION
**Pull request by tobias-johansson**
Now able to bootstrap on JDK7, but I am unable to verify completely due to #54 
How is that CI coming along? :)

Not sure whether to keep any JDK version check in launcher script. Is JDK6 a target?

### CODE REVIEW

**Comment by cvogt** [comment]
#54 has been fixed :)

**Comment by cvogt** [comment]
LGTM

**Comment by tobias-johansson** [comment]
Ok, i'll update and try to verify :)

**Comment by cvogt** [comment]
just go to latest master :)

**Comment by tobias-johansson** [comment]
ok great!

**Comment by tobias-johansson** [comment]
FYI, can now bootstrap and compile/run test projects on JDK7 and JDK8

**Comment by cvogt** [comment]
Awesome :)!

**Pull request merged**
