### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by ritschwumm**

### CODE REVIEW

**Comment by ritschwumm** [comment]
oh, CLA? sorry, please ignore this PR then.

**Comment by cvogt** [comment]
@ritschwumm the CLA only says "I, the contributor, agree to licence my contributions to this project under the terms of the Apache 2.0.", which is the enclosed FOSS license. I added the CLA upon advice from @fommil, who is a big FOSS advocate. Nothing proprietary involved, if that's your concern.

**Comment by fommil** [comment]
these changes are trivial, you don't need a CLA for them.

**Comment by cvogt** [comment]
@ritschwumm ok. if you re-open I'll merge without asking to sign the CLA :)

**Comment by cvogt** [comment]
(thx @fommil )

**Pull request closed without merging**
